apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata: 
  name: main-rules
  namespace: monitoring
  labels:
    app: kube-prometheus-stack
    release: prometheus
spec:
  groups:
  - name: main.rules
    rules:
    - alert: HostHighCpuLoad
      expr: 100 - (avg by(instance) (rate(node_cpu_seconds_total{mode="idle"}[2m])) * 100) > 13
      labels:
        severity: warning
        namespace: monitoring
      annotations:
        description: "CPU load on host is over 75% \n Value = {{ $value }}\n"
        summary: "High CPU load on host !"
