apiVersion: v1

kind: Secret
metadata:
  name: {{ .Values.db_secret.name }}
  
type: Opaque

data:
  # This is 'khalil' but base64 encoded, it's how secrets work in kubernetes
  MYSQL_ROOT_PASSWORD: a2hhbGlsCg==
  MYSQL_PASSWORD: a2hhbGlsCg==

