apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.GolangDeployment.service.name }}
spec:
  selector:
    app: {{ .Values.GolangDeployment.service.name }}  
  type: {{ .Values.GolangDeployment.service.type }}
  ports:
    - protocol: {{ .Values.GolangDeployment.service.protocol }}
      port: {{ .Values.GolangDeployment.service.port }}
      targetPort: {{ .Values.GolangDeployment.service.targetPort }}  
