apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.mysqlStatefulSet.service.name }}
spec:
  selector:
    app: {{ .Values.mysqlStatefulSet.service.name }}
  ports:
  - protocol: {{ .Values.mysqlStatefulSet.service.protocol }}  
    port: {{ .Values.mysqlStatefulSet.service.port }}
    targetPort: {{ .Values.mysqlStatefulSet.service.targetPort }}
